spring.application.name=TonightsCall

spring.mongodb.uri=mongodb://localhost:27017,10.1.1.45:27017,10.1.1.44:27017/TonightsCall?replicaSet=lsmdb&readPreference=primary

spring.neo4j.uri=bolt://10.1.1.44:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=neo4jPassword

jwt.secret = iqjUzlfSdjO5euZnZr6oou0mCxGAEtb2P1WZyew8g0T
jwt.validityTime = 3600000
jwt.issuer = MySpringApp

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
