package it.unipi.tonightscall.DTO;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.util.Map;

/**
 * Data Transfer Object (DTO) containing analytics and statistics for an event.
 * <p>
 * This class provides insights such as attendee demographics, financial projections,
 * and attendance counts.
 * </p>
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Schema(description = "Model representing statistical analytics for an event")
public class StatisticsDTO {

    /**
     * The date when these statistics were last calculated or updated.
     */
    @JsonProperty("date_update")
    @Schema(description = "Last update date of the statistics (ISO 8601)", type = "string", format = "date", example = "2024-06-01")
    private LocalDate dateUpdate;

    /**
     * The average age of the attendees.
     */
    @JsonProperty("average_age")
    @Schema(description = "Average age of the event attendees", example = "24.5")
    private double averageAge;

    /**
     * The predicted revenue or income generated by the event.
     */
    @JsonProperty("predicted_income")
    @Schema(description = "Estimated financial revenue from the event", example = "15000.00")
    private double predictedIncome;

    /**
     * A map representing the geographical origin of attendees.
     * Key: City or Region name.
     * Value: Number of attendees from that location.
     */
    @JsonProperty("origin_attenders")
    @Schema(
            description = "Breakdown of attendees by origin (City -> Count)",
            example = "{\"Pisa\": 120, \"Florence\": 45, \"Lucca\": 10}"
    )
    private Map<String, Integer> originAttenders;

    /**
     * The total number of attendees (actual or registered).
     */
    @JsonProperty("total_attenders")
    @Schema(description = "Total number of attendees", example = "175")
    private int totalAttenders;
}
