package it.unipi.tonightscall.entity.document;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.mongodb.core.mapping.Field;

import java.time.LocalDate;
import java.util.Map;

/**
 * Embedded entity containing analytics and statistics for an event.
 * <p>
 * This class provides insights such as attendee demographics, financial projections,
 * and attendance counts.
 * </p>
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
public class Statistics {

    /**
     * The date when these statistics were last calculated or updated.
     */
    @Field("date_update")
    private LocalDate dateUpdate;

    /**
     * The average age of the attendees.
     */
    @Field("average_age")
    private double averageAge;

    /**
     * The predicted revenue or income generated by the event.
     */
    @Field("predicted_income")
    private double predictedIncome;

    /**
     * A map representing the geographical origin of attendees.
     * Key: City or Region name.
     * Value: Number of attendees from that location.
     */
    @Field("origin_attenders")
    private Map<String, Integer> originAttenders;

    /**
     * The total number of attendees (actual or registered).
     */
    @Field("total_attenders")
    private int totalAttenders;

    /**
     * Flags that indicates if the statistics can be published or not
     */
    @Field("publish")
    private boolean publish;
}
